name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path -Path "requirements.txt") { python -m pip install -r requirements.txt } else { echo "No requirements.txt" }
      shell: pwsh

    - name: Run syntax check
      run: |
        python -m compileall .
      shell: python

    - name: Quick smoke import
      run: |
        python -c "import app; print('ok')"
      shell: python
